version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    groups:
      androidx:
        patterns:
          - "androidx.*"
      kotlinx:
        patterns:
          - "org.jetbrains.kotlinx:*"
      compose:
        patterns:
          - "androidx.compose:*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    groups:
      actions:
        patterns:
          - "*"
